In [417]:
import pandas as pd
import json
import csv

In [418]:
users = pd.read_json('https://raw.githubusercontent.com/Gops319/Fetch_AE_Takehome/main/users.json',lines=True)

In [419]:
users

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
1,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
2,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
3,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
4,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
...,...,...,...,...,...,...,...
490,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
491,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
492,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
493,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
494,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN

In [420]:
def extract_value(row, key):
    value = row.get(key) if isinstance(row, dict) else None
    if value and key == '$date':
        return str(value)
    return value

In [421]:
# Extracting '_id', 'createdDate', 'lastLogin' columns
users['_id'] = users['_id'].apply(lambda x: extract_value(x, '$oid'))
users['createdDate'] = users['createdDate'].apply(lambda x: extract_value(x, '$date'))
users['lastLogin'] = users['lastLogin'].apply(lambda x: extract_value(x, '$date'))

In [422]:
# Converting 'createdDate' and 'lastLogin' to datetime
users['createdDate'] = pd.to_datetime(users['createdDate'], unit='ms')
users['lastLogin'] = pd.to_datetime(users['lastLogin'], unit='ms')
date_columns = ['createdDate', 'lastLogin']
for column in date_columns:
  users[column] = pd.to_datetime(users[column], errors='coerce').where(pd.notnull(users[column]), None)

<ipython-input-422-b52b53da90da>:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  users['createdDate'] = pd.to_datetime(users['createdDate'], unit='ms')
<ipython-input-422-b52b53da90da>:3: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  users['lastLogin'] = pd.to_datetime(users['lastLogin'], unit='ms')

In [423]:
users

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,consumer,Email,WI
1,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,consumer,Email,WI
2,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,consumer,Email,WI
3,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,consumer,Email,WI
4,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,consumer,Email,WI
...,...,...,...,...,...,...,...
490,54943462e4b07e684157a532,True,2014-12-19 14:20:41.344,2021-03-05 16:52:26.752,fetch-staff,NaN,NaN
491,54943462e4b07e684157a532,True,2014-12-19 14:20:41.344,2021-03-05 16:52:26.752,fetch-staff,NaN,NaN
492,54943462e4b07e684157a532,True,2014-12-19 14:20:41.344,2021-03-05 16:52:26.752,fetch-staff,NaN,NaN
493,54943462e4b07e684157a532,True,2014-12-19 14:20:41.344,2021-03-05 16:52:26.752,fetch-staff,NaN,NaN
494,54943462e4b07e684157a532,True,2014-12-19 14:20:41.344,2021-03-05 16:52:26.752,fetch-staff,NaN,NaN

In [424]:
users = users.rename(columns={'_id': 'userId'})

In [425]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   userId        495 non-null    object
 1   active        495 non-null    bool
 2   createdDate   495 non-null    datetime64[ns]
 3   lastLogin     433 non-null    datetime64[ns]
 4   role          495 non-null    object
 5   signUpSource  447 non-null    object
 6   state         439 non-null    object
dtypes: bool(1), datetime64[ns](2), object(4)
memory usage: 23.8+ KB

In [426]:
# Removing duplicate records
initial_record_count = len(users)
users.drop_duplicates(inplace=True)
final_record_count = len(users)
print(f"Number of records before removing duplicates: {initial_record_count}")
print(f"Number of records after removing duplicates: {final_record_count}")

# Checking for null or duplicate values in userId
user_id_null_count = users['userId'].isnull().sum()
user_id_duplicate_count = users['userId'].duplicated().sum()
print(f"Number of null values in userId: {user_id_null_count}")
print(f"Number of duplicate values in userId: {user_id_duplicate_count}")


#Checking for any invalid data in createdDate and lastLogin columns
invalid_date_records = users[users['createdDate'] > users['lastLogin']]
print(f"Records where createdDate is later than lastLogin date:\n{invalid_date_records}")

#Checking the unique values in the column 'role'
unique_role_values = users['role'].unique()
print(f"Unique values in 'role' column: {unique_role_values}")

#Checking the unique values in the column 'signupSource'
unique_sign_up_sources = users['signUpSource'].unique()
print(f"Unique values in 'signUpSource' column: {unique_sign_up_sources}")

# Ensuring 'active' column contains only boolean values
unique_active_values = users['active'].unique()
print(f"Unique values in 'active' column: {unique_active_values}")

#Checking null values in columns createdDate and lastLogin columns
createdDate_null_values = users[users['createdDate'].isnull()][['userId', 'createdDate']]
lastLogin_null_values = users[users['lastLogin'].isnull()][['userId','lastLogin']]
print(f"Records with null values in createdDate column:\n{createdDate_null_values}")
print(f"Records with null values in lastLogin column:\n{lastLogin_null_values}")

# Validating 'state' column
valid_state_codes = set(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'])
invalid_states = users[~users['state'].isin(valid_state_codes) | users['state'].isnull()][['userId', 'state']]
print(f"Records with null values in the 'state' column:\n{invalid_states}")

Number of records before removing duplicates: 495
Number of records after removing duplicates: 212
Number of null values in userId: 0
Number of duplicate values in userId: 0
Records where createdDate is later than lastLogin date:
Empty DataFrame
Columns: [userId, active, createdDate, lastLogin, role, signUpSource, state]
Index: []
Unique values in 'role' column: ['consumer' 'fetch-staff']
Unique values in 'signUpSource' column: ['Email' 'Google' nan]
Unique values in 'active' column: [ True False]
Records with null values in createdDate column:
Empty DataFrame
Columns: [userId, createdDate]
Index: []
Records with null values in lastLogin column:
                       userId lastLogin
97   5ff616a68f142f11dd189163       NaT
143  5ffe115404929101d0aaebb2       NaT
170  5e27526d0bdb6a138c32b556       NaT
180  6002475cfb296c121a81b98d       NaT
181  60024f24e257124ec6b99a13       NaT
182  60037329e257124ec6b99eeb       NaT
183  6000b75bbe5fc96dfee1d4d3       NaT
184  6002541ae257124ec6b99a3a       NaT
186  600258dafb296c4ef805d9b7       NaT
187  60025c65fb296c4ef805d9e6       NaT
188  60037005e257124ec6b99ec2       NaT
195  60023de5fb296c121a81b955       NaT
197  60049cdce257124ec6b9a353       NaT
198  60025fe0e257124ec6b99a87       NaT
199  600498c4e257124ec6b9a331       NaT
200  6004a5d3fb296c4ef805e256       NaT
201  60037a94fb296c4ef805ddbe       NaT
202  600495c3fb296c4ef805e1fc       NaT
203  6004a965e257124ec6b9a39f       NaT
223  6006f786fb296c7f688530f8       NaT
228  6008896c633aab121bb8e11d       NaT
247  6008f02fb6310511daa4f314       NaT
251  6009e60450b3311194385009       NaT
253  6008d447b6310511daa4f281       NaT
256  60099c1450b33111fd61f702       NaT
258  6008e9cdb6310511daa4f2e4       NaT
260  600a03e17d983a124e9adb0f       NaT
263  600992d17d983a11f63d11ad       NaT
264  600b477e7d983a124e9ae061       NaT
271  600f20c15edb787dce060911       NaT
279  600eea525edb7811cde6c81c       NaT
325  600f00d05edb787dce05fb84       NaT
330  600f19914329897eac238fef       NaT
335  600f35015edb782098e2ac1b       NaT
344  60145ff384231211ce796d51       NaT
351  60147d2ac8b50e11d8453f53       NaT
375  60186237c8b50e11d8454d5f       NaT
379  60183e6c9a1b091205b61b49       NaT
389  60217fa799409b11fcf899fe       NaT
420  5fb0a078be5fc9775c1f3945       NaT
Records with null values in the 'state' column:
                       userId state
344  60145ff384231211ce796d51   NaN
375  60186237c8b50e11d8454d5f   NaN
422  5a43c08fe4b014fd6b6a0612   NaN
432  5fbc35711d967d1222cbfefc   NaN
455  5fa41775898c7a11a6bcef3e   NaN
475  54943462e4b07e684157a532   NaN

In [427]:
null_values_count = users.isnull().sum()
null_values_count

userId           0
active           0
createdDate      0
lastLogin       40
role             0
signUpSource     5
state            6
dtype: int64

In [428]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 212 entries, 0 to 475
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   userId        212 non-null    object
 1   active        212 non-null    bool
 2   createdDate   212 non-null    datetime64[ns]
 3   lastLogin     172 non-null    datetime64[ns]
 4   role          212 non-null    object
 5   signUpSource  207 non-null    object
 6   state         206 non-null    object
dtypes: bool(1), datetime64[ns](2), object(4)
memory usage: 11.8+ KB

In [429]:
users.to_csv("users.csv",index=False)

In [430]:
brands = pd.read_json('https://raw.githubusercontent.com/Gops319/Fetch_AE_Takehome/main/brands.json',lines=True)

In [431]:
brands

,_id,barcode,category,categoryCode,cpg,name,topBrand,brandCode
0,{'$oid': '601ac115be37ce2ead437551'},511111019862,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0,NaN
1,{'$oid': '601c5460be37ce2ead43755f'},511111519928,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0,STARBUCKS
2,{'$oid': '601ac142be37ce2ead43755d'},511111819905,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176
3,{'$oid': '601ac142be37ce2ead43755a'},511111519874,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051
4,{'$oid': '601ac142be37ce2ead43755e'},511111319917,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827
...,...,...,...,...,...,...,...,...
1162,{'$oid': '5f77274dbe37ce6b592e90c0'},511111116752,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f77274dbe37...",test brand @1601644365844,NaN,NaN
1163,{'$oid': '5dc1fca91dda2c0ad7da64ae'},511111706328,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368ab...",Dippin DotsÂ® Cereal,NaN,DIPPIN DOTS CEREAL
1164,{'$oid': '5f494c6e04db711dd8fe87e7'},511111416173,Candy & Sweets,CANDY_AND_SWEETS,"{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b0...",test brand @1598639215217,NaN,TEST BRANDCODE @1598639215217
1165,{'$oid': '5a021611e4b00efe02b02a57'},511111400608,Grocery,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",LIPTON TEA Leaves,0.0,LIPTON TEA Leaves
1166,{'$oid': '6026d757be37ce6369301468'},511111019930,Baking,BAKING,"{'$id': {'$oid': '6026d757be37ce6369301467'}, ...",test brand @1613158231643,0.0,TEST BRANDCODE @1613158231644

In [432]:
def extract_info(row):
    brandId = extract_value(row['_id'], '$oid')
    cpgId = extract_value(row['cpg'].get('$id'), '$oid') if isinstance(row['cpg'], dict) else None
    cpgRef = extract_value(row['cpg'], '$ref') if isinstance(row['cpg'], dict) else None
    return brandId, cpgId, cpgRef

In [433]:
brands[['brandId', 'cpgId', 'cpgRef']] = brands.apply(lambda row: pd.Series(extract_info(row)), axis=1)

# Dropping the original '_id' and 'cpg' columns
brands = brands.drop(columns=['_id', 'cpg'])

In [434]:
brands

,barcode,category,categoryCode,name,topBrand,brandCode,brandId,cpgId,cpgRef
0,511111019862,Baking,BAKING,test brand @1612366101024,0.0,NaN,601ac115be37ce2ead437551,601ac114be37ce2ead437550,Cogs
1,511111519928,Beverages,BEVERAGES,Starbucks,0.0,STARBUCKS,601c5460be37ce2ead43755f,5332f5fbe4b03c9a25efd0ba,Cogs
2,511111819905,Baking,BAKING,test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176,601ac142be37ce2ead43755d,601ac142be37ce2ead437559,Cogs
3,511111519874,Baking,BAKING,test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051,601ac142be37ce2ead43755a,601ac142be37ce2ead437559,Cogs
4,511111319917,Candy & Sweets,CANDY_AND_SWEETS,test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827,601ac142be37ce2ead43755e,5332fa12e4b03c9a25efd1e7,Cogs
...,...,...,...,...,...,...,...,...,...
1162,511111116752,Baking,BAKING,test brand @1601644365844,NaN,NaN,5f77274dbe37ce6b592e90c0,5f77274dbe37ce6b592e90bf,Cogs
1163,511111706328,Breakfast & Cereal,NaN,Dippin DotsÂ® Cereal,NaN,DIPPIN DOTS CEREAL,5dc1fca91dda2c0ad7da64ae,53e10d6368abd3c7065097cc,Cogs
1164,511111416173,Candy & Sweets,CANDY_AND_SWEETS,test brand @1598639215217,NaN,TEST BRANDCODE @1598639215217,5f494c6e04db711dd8fe87e7,5332fa12e4b03c9a25efd1e7,Cogs
1165,511111400608,Grocery,NaN,LIPTON TEA Leaves,0.0,LIPTON TEA Leaves,5a021611e4b00efe02b02a57,5332f5f6e4b03c9a25efd0b4,Cogs
1166,511111019930,Baking,BAKING,test brand @1613158231643,0.0,TEST BRANDCODE @1613158231644,6026d757be37ce6369301468,6026d757be37ce6369301467,Cogs

In [435]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   barcode       1167 non-null   int64
 1   category      1012 non-null   object
 2   categoryCode  517 non-null    object
 3   name          1167 non-null   object
 4   topBrand      555 non-null    float64
 5   brandCode     933 non-null    object
 6   brandId       1167 non-null   object
 7   cpgId         1167 non-null   object
 8   cpgRef        1167 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 82.2+ KB

In [436]:
# Converting values in 'topBrand' column to boolean
brands['topBrand'] = brands['topBrand'].replace({1: True, 0: False})

# Removing duplicate records
initial_record_count = len(brands)
brands.drop_duplicates(inplace=True)
final_record_count = len(brands)
print(f"Number of records before removing duplicates: {initial_record_count}")
print(f"Number of records after removing duplicates: {final_record_count}")

# Checking for null or duplicate values in brandId
brand_id_null_count = brands['brandId'].isnull().sum()
brand_id_duplicate_count = brands['brandId'].duplicated().sum()
print(f"Number of null values in brandId: {brand_id_null_count}")
print(f"Number of duplicate values in brandId: {brand_id_duplicate_count}")

# Ensuring 'topBrand' column contains only boolean values
unique_topBrand_values = brands['topBrand'].unique()
print(f"Unique values in 'topBrand' column: {unique_topBrand_values}")
brands['topBrand'] = brands['topBrand'].astype('boolean')
brands['topBrand'] = brands['topBrand'].where(pd.notnull(brands['topBrand']), None)

null_values_count = brands.isnull().sum()
null_values_count

Number of records before removing duplicates: 1167
Number of records after removing duplicates: 1167
Number of null values in brandId: 0
Number of duplicate values in brandId: 0
Unique values in 'topBrand' column: [False nan True]

barcode           0
category        155
categoryCode    650
name              0
topBrand        612
brandCode       234
brandId           0
cpgId             0
cpgRef            0
dtype: int64

In [437]:
# Find the number of unique values for the specified columns
unique_categoryCode_values = brands['categoryCode'].nunique()
unique_category_values = brands['category'].nunique()
unique_barcode_values = brands['barcode'].nunique()
unique_brandCode_values = brands['brandCode'].nunique()

# Display the number of unique values for each column
print("Number of unique values in 'categoryCode' column:", unique_categoryCode_values)
print("Number of unique values in 'category' column:", unique_category_values)
print("Number of unique values in 'barcode' column:", unique_barcode_values)
print("Number of unique values in 'brandCode' column:", unique_brandCode_values)


duplicate_barcodes = brands[brands.duplicated(subset=['barcode'], keep=False)]

# Find records where brandCode column has nulls or zeros
null_or_zero_brandcode = brands[(brands['brandCode'].isnull()) | (brands['brandCode'] == 0)]

# Get the count of each occurrence
duplicate_barcodes_count = duplicate_barcodes.shape[0]
null_or_zero_brandcode_count = null_or_zero_brandcode.shape[0]
# Display the number of unique values for each column
print("Number of duplicate barcode values:", duplicate_barcodes_count)
print("Number of duplicate brandcode values:", null_or_zero_brandcode_count)
null_or_zero_brandcode

Number of unique values in 'categoryCode' column: 14
Number of unique values in 'category' column: 23
Number of unique values in 'barcode' column: 1160
Number of unique values in 'brandCode' column: 897
Number of duplicate barcode values: 14
Number of duplicate brandcode values: 234

,barcode,category,categoryCode,name,topBrand,brandCode,brandId,cpgId,cpgRef
0,511111019862,Baking,BAKING,test brand @1612366101024,False,NaN,601ac115be37ce2ead437551,601ac114be37ce2ead437550,Cogs
11,511111102540,NaN,NaN,MorningStar,<NA>,NaN,57c08106e4b0718ff5fcb02c,5332f5f2e4b03c9a25efd0aa,Cpgs
18,511111317364,Baking,BAKING,test brand @1605535049181,False,NaN,5fb28549be37ce522e165cb5,5fb28549be37ce522e165cb4,Cogs
23,511111303947,NaN,NaN,Bottled Starbucks,<NA>,NaN,5332f5fee4b03c9a25efd0bd,53e10d6368abd3c7065097cc,Cpgs
24,511111802914,NaN,NaN,Full Throttle,<NA>,NaN,5332fa7ce4b03c9a25efd22e,5332f5ebe4b03c9a25efd0a8,Cpgs
...,...,...,...,...,...,...,...,...,...
1135,511111405184,NaN,NaN,Do It Yourself,<NA>,NaN,5d658fca6d5f3b23d1bc7912,53e10d6368abd3c7065097cc,Cogs
1144,511111202516,NaN,NaN,Corona,<NA>,NaN,57c08242e4b0718ff5fcb032,5332f7a7e4b03c9a25efd134,Cpgs
1146,511111703105,NaN,NaN,Bellatoria,<NA>,NaN,5332fa12e4b03c9a25efd1e6,5332fa12e4b03c9a25efd1e7,Cpgs
1157,511111303015,NaN,NaN,DASANI,<NA>,NaN,5332fa75e4b03c9a25efd221,5332f5ebe4b03c9a25efd0a8,Cpgs
1162,511111116752,Baking,BAKING,test brand @1601644365844,<NA>,NaN,5f77274dbe37ce6b592e90c0,5f77274dbe37ce6b592e90bf,Cogs

In [438]:
brands

,barcode,category,categoryCode,name,topBrand,brandCode,brandId,cpgId,cpgRef
0,511111019862,Baking,BAKING,test brand @1612366101024,False,NaN,601ac115be37ce2ead437551,601ac114be37ce2ead437550,Cogs
1,511111519928,Beverages,BEVERAGES,Starbucks,False,STARBUCKS,601c5460be37ce2ead43755f,5332f5fbe4b03c9a25efd0ba,Cogs
2,511111819905,Baking,BAKING,test brand @1612366146176,False,TEST BRANDCODE @1612366146176,601ac142be37ce2ead43755d,601ac142be37ce2ead437559,Cogs
3,511111519874,Baking,BAKING,test brand @1612366146051,False,TEST BRANDCODE @1612366146051,601ac142be37ce2ead43755a,601ac142be37ce2ead437559,Cogs
4,511111319917,Candy & Sweets,CANDY_AND_SWEETS,test brand @1612366146827,False,TEST BRANDCODE @1612366146827,601ac142be37ce2ead43755e,5332fa12e4b03c9a25efd1e7,Cogs
...,...,...,...,...,...,...,...,...,...
1162,511111116752,Baking,BAKING,test brand @1601644365844,<NA>,NaN,5f77274dbe37ce6b592e90c0,5f77274dbe37ce6b592e90bf,Cogs
1163,511111706328,Breakfast & Cereal,NaN,Dippin DotsÂ® Cereal,<NA>,DIPPIN DOTS CEREAL,5dc1fca91dda2c0ad7da64ae,53e10d6368abd3c7065097cc,Cogs
1164,511111416173,Candy & Sweets,CANDY_AND_SWEETS,test brand @1598639215217,<NA>,TEST BRANDCODE @1598639215217,5f494c6e04db711dd8fe87e7,5332fa12e4b03c9a25efd1e7,Cogs
1165,511111400608,Grocery,NaN,LIPTON TEA Leaves,False,LIPTON TEA Leaves,5a021611e4b00efe02b02a57,5332f5f6e4b03c9a25efd0b4,Cogs
1166,511111019930,Baking,BAKING,test brand @1613158231643,False,TEST BRANDCODE @1613158231644,6026d757be37ce6369301468,6026d757be37ce6369301467,Cogs

In [439]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   barcode       1167 non-null   int64
 1   category      1012 non-null   object
 2   categoryCode  517 non-null    object
 3   name          1167 non-null   object
 4   topBrand      555 non-null    boolean
 5   brandCode     933 non-null    object
 6   brandId       1167 non-null   object
 7   cpgId         1167 non-null   object
 8   cpgRef        1167 non-null   object
dtypes: boolean(1), int64(1), object(7)
memory usage: 75.3+ KB

In [440]:
brands.to_csv("brands.csv",index=False)

In [441]:
receipts = pd.read_json('https://raw.githubusercontent.com/Gops319/Fetch_AE_Takehome/main/receipts.json',lines=True)

In [442]:
receipts

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,{'$oid': '5ff1e1d20a7214ada1000561'},5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1114,{'$oid': '603cc0630a720fde100003e6'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614594147000},{'$date': 1614594147000},NaN,{'$date': 1614594148000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1115,{'$oid': '603d0b710a720fde1000042a'},NaN,NaN,{'$date': 1614613361873},{'$date': 1614613361873},NaN,{'$date': 1614613361873},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1116,{'$oid': '603cf5290a720fde10000413'},NaN,NaN,{'$date': 1614607657664},{'$date': 1614607657664},NaN,{'$date': 1614607657664},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},NaN,{'$date': 1614604049000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1118,{'$oid': '603c4fea0a7217c72c000389'},NaN,NaN,{'$date': 1614565354962},{'$date': 1614565354962},NaN,{'$date': 1614565354962},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

In [443]:
# Extracting '_id', 'createdDate', 'lastLogin' columns
nested_columns=['_id','createDate','dateScanned','finishedDate','modifyDate','pointsAwardedDate','purchaseDate']
for column in nested_columns:
  if column=='_id':
    key='$oid'
  else:
    key='$date'
  receipts[column]=receipts[column].apply(extract_value,key=key)

receipts = receipts.rename(columns = {"_id":"receiptId"})


date_columns = ['createDate', 'dateScanned', 'finishedDate','modifyDate', 'pointsAwardedDate', 'purchaseDate']
for column in date_columns:
    receipts[column] = pd.to_datetime(receipts[column], unit='ms')
    receipts[column] = pd.to_datetime(receipts[column], errors='coerce').where(pd.notnull(receipts[column]), None)

<ipython-input-443-f11f85325253>:15: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  receipts[column] = pd.to_datetime(receipts[column], unit='ms')
<ipython-input-443-f11f85325253>:15: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  receipts[column] = pd.to_datetime(receipts[column], unit='ms')
<ipython-input-443-f11f85325253>:15: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  receipts[column] = pd.to_datetime(receipts[column], unit='ms')
<ipython-input-443-f11f85325253>:15: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  receipts[column] = pd.to_datetime(receipts[column], unit='ms')
<ipython-input-443-f11f85325253>:15: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  receipts[column] = pd.to_datetime(receipts[column], unit='ms')
<ipython-input-443-f11f85325253>:15: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  receipts[column] = pd.to_datetime(receipts[column], unit='ms')

In [444]:
receipts

,receiptId,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,500.0,2021-01-03 00:00:55.296,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,150.0,2021-01-02 15:25:22.304,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,NaT,2021-01-03 15:24:58.752,NaT,5.0,2021-01-03 00:00:55.296,1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,5.0,2021-01-03 00:00:55.296,4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,5.0,2021-01-02 15:25:22.304,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1114,603cc0630a720fde100003e6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:22:59.072,2021-03-01 10:22:59.072,NaT,2021-03-01 10:22:59.072,NaT,25.0,2020-08-17 00:00:52.224,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1115,603d0b710a720fde1000042a,NaN,NaN,2021-03-01 15:41:55.584,2021-03-01 15:41:55.584,NaT,2021-03-01 15:41:55.584,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1116,603cf5290a720fde10000413,NaN,NaN,2021-03-01 14:07:59.488,2021-03-01 14:07:59.488,NaT,2021-03-01 14:07:59.488,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 13:06:49.472,2021-03-01 13:06:49.472,NaT,2021-03-01 13:06:49.472,NaT,25.0,2020-08-17 00:00:52.224,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1118,603c4fea0a7217c72c000389,NaN,NaN,2021-03-01 02:22:23.232,2021-03-01 02:22:23.232,NaT,2021-03-01 02:22:23.232,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

In [445]:
rewards_items=[]
for idx, row in receipts.iterrows():
    receipt_id = row["receiptId"]
    items = row["rewardsReceiptItemList"]

    # Ensure items is a list before iterating
    if isinstance(items, list):
        for item in items:
            item["receiptId"] = receipt_id
            rewards_items.append(item)

items=pd.DataFrame(rewards_items)
receipts = receipts.drop(columns=['rewardsReceiptItemList',])

In [446]:
receipts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1119 entries, 0 to 1118
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   receiptId                1119 non-null   object
 1   bonusPointsEarned        544 non-null    float64
 2   bonusPointsEarnedReason  544 non-null    object
 3   createDate               1119 non-null   datetime64[ns]
 4   dateScanned              1119 non-null   datetime64[ns]
 5   finishedDate             568 non-null    datetime64[ns]
 6   modifyDate               1119 non-null   datetime64[ns]
 7   pointsAwardedDate        537 non-null    datetime64[ns]
 8   pointsEarned             609 non-null    float64
 9   purchaseDate             671 non-null    datetime64[ns]
 10  purchasedItemCount       635 non-null    float64
 11  rewardsReceiptStatus     1119 non-null   object
 12  totalSpent               684 non-null    float64
 13  userId                   1119 non-null   object
dtypes: datetime64[ns](6), float64(4), object(4)
memory usage: 122.5+ KB

In [447]:
# Removing duplicate records
initial_record_count = len(receipts)
receipts.drop_duplicates(inplace=True)
final_record_count = len(receipts)
print(f"Number of records before removing duplicates: {initial_record_count}")
print(f"Number of records after removing duplicates: {final_record_count}")

# Checking for null or duplicate values in receiptId
receipt_id_null_count = receipts['receiptId'].isnull().sum()
receipt_id_duplicate_count = receipts['receiptId'].duplicated().sum()
print(f"Number of null values in receiptId: {receipt_id_null_count}")
print(f"Number of duplicate values in receiptId: {receipt_id_duplicate_count}")

#Checking the unique values in the column 'rewardsReceiptStatus'
unique_status_values = receipts['rewardsReceiptStatus'].unique()
print(f"Unique values in 'rewards receipt status' column: {unique_status_values}")


# Find user IDs from receipts that are not present in the user table
missing_user_ids = receipts[~receipts['userId'].isin(users['userId'])]
missing_user_count = len(missing_user_ids)

# Display the missing user IDs and count
print("Missing User IDs:")
print(missing_user_ids[['userId']])
print("\nNumber of Missing User IDs:", missing_user_count)

#Dropping the userIds which are not present in users table
receipts = receipts.drop(missing_user_ids.index)

Number of records before removing duplicates: 1119
Number of records after removing duplicates: 1119
Number of null values in receiptId: 0
Number of duplicate values in receiptId: 0
Unique values in 'rewards receipt status' column: ['FINISHED' 'REJECTED' 'FLAGGED' 'SUBMITTED' 'PENDING']
Missing User IDs:
                       userId
13   5f9c74f7c88c1415cbddb839
15   5ff1e1e9b6a9d73a3a9f10f6
16   5ff1e1dfcfcf6c399c274ab3
20   5f9c74e3f1937815bd2c1d73
21   5ff1e196cfcf6c399c274a38
..                        ...
955  60253861efa6017a44dc6b50
956  60253891b54593795bf69242
966  60253891b54593795bf69242
985  60268c7bb545931ac63683af
990  60268c78efa6011bb151077d

[148 rows x 1 columns]

Number of Missing User IDs: 148

In [448]:
#Checking for any invalid data in createdDate and lastLogin columns
invalid_date_records = receipts[receipts['purchaseDate'] > receipts['pointsAwardedDate']]
print(f"Records where purchaseDate is later than pointsAwardedDate date:\n{invalid_date_records}")

Records where purchaseDate is later than pointsAwardedDate date:
                    receiptId  bonusPointsEarned  \
14   5ff1e1b20a7214ada100055a              300.0
85   5ff4ce640a7214ada10005e0               25.0
362  600887560a720f05fa000098              250.0
553  60145a3d0a7214ad50000082              750.0

                               bonusPointsEarnedReason  \
14   Receipt number 4 completed, bonus point schedu...
85                         COMPLETE_NONPARTNER_RECEIPT
362  Receipt number 3 completed, bonus point schedu...
553  Receipt number 1 completed, bonus point schedu...

                 createDate             dateScanned            finishedDate  \
14  2021-01-03 15:24:58.752 2021-01-03 15:24:58.752 2021-01-03 15:24:58.752
85  2021-01-05 20:38:46.016 2021-01-05 20:38:46.016 2021-01-05 20:38:46.016
362 2021-01-20 19:40:27.008 2021-01-20 19:40:27.008 2021-01-20 19:40:27.008
553 2021-01-29 18:55:24.672 2021-01-29 18:55:24.672 2021-01-29 18:55:24.672

                 modifyDate       pointsAwardedDate  pointsEarned  \
14  2021-01-03 15:24:58.752 2021-01-03 15:24:58.752         300.0
85  2021-01-05 20:38:46.016 2021-01-05 20:38:46.016          25.0
362 2021-01-20 19:40:27.008 2021-01-20 19:40:27.008         250.0
553 2021-01-29 18:55:24.672 2021-01-29 18:55:24.672         750.0

               purchaseDate  purchasedItemCount rewardsReceiptStatus  \
14  2021-02-03 15:23:44.000                 1.0             FINISHED
85  2021-02-05 20:39:42.336                 1.0             FINISHED
362 2021-02-20 19:41:23.328                 1.0             FINISHED
553 2021-02-28 18:56:44.544                 1.0             FINISHED

     totalSpent                    userId
14          1.0  5ff1e194b6a9d73a3a9f1052
85          1.0  5ff4ce33c3d63511e2a484b6
362         1.0  6008873eb6310511daa4e8eb
553         1.0  60145a3c84231211ce796c5d

In [449]:
null_values_count = receipts.isnull().sum()
null_values_count

receiptId                    0
bonusPointsEarned          553
bonusPointsEarnedReason    553
createDate                   0
dateScanned                  0
finishedDate               512
modifyDate                   0
pointsAwardedDate          552
pointsEarned               495
purchaseDate               434
purchasedItemCount         480
rewardsReceiptStatus         0
totalSpent                 431
userId                       0
dtype: int64

In [450]:
receipts

,receiptId,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptStatus,totalSpent,userId
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,500.0,2021-01-03 00:00:55.296,5.0,FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,150.0,2021-01-02 15:25:22.304,2.0,FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,NaT,2021-01-03 15:24:58.752,NaT,5.0,2021-01-03 00:00:55.296,1.0,REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,5.0,2021-01-03 00:00:55.296,4.0,FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,2021-01-03 15:24:58.752,5.0,2021-01-02 15:25:22.304,2.0,FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1114,603cc0630a720fde100003e6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:22:59.072,2021-03-01 10:22:59.072,NaT,2021-03-01 10:22:59.072,NaT,25.0,2020-08-17 00:00:52.224,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
1115,603d0b710a720fde1000042a,NaN,NaN,2021-03-01 15:41:55.584,2021-03-01 15:41:55.584,NaT,2021-03-01 15:41:55.584,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1116,603cf5290a720fde10000413,NaN,NaN,2021-03-01 14:07:59.488,2021-03-01 14:07:59.488,NaT,2021-03-01 14:07:59.488,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 13:06:49.472,2021-03-01 13:06:49.472,NaT,2021-03-01 13:06:49.472,NaT,25.0,2020-08-17 00:00:52.224,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
1118,603c4fea0a7217c72c000389,NaN,NaN,2021-03-01 02:22:23.232,2021-03-01 02:22:23.232,NaT,2021-03-01 02:22:23.232,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

In [451]:
receipts.info()

<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 1118
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   receiptId                971 non-null    object
 1   bonusPointsEarned        418 non-null    float64
 2   bonusPointsEarnedReason  418 non-null    object
 3   createDate               971 non-null    datetime64[ns]
 4   dateScanned              971 non-null    datetime64[ns]
 5   finishedDate             459 non-null    datetime64[ns]
 6   modifyDate               971 non-null    datetime64[ns]
 7   pointsAwardedDate        419 non-null    datetime64[ns]
 8   pointsEarned             476 non-null    float64
 9   purchaseDate             537 non-null    datetime64[ns]
 10  purchasedItemCount       491 non-null    float64
 11  rewardsReceiptStatus     971 non-null    object
 12  totalSpent               540 non-null    float64
 13  userId                   971 non-null    object
dtypes: datetime64[ns](6), float64(4), object(4)
memory usage: 113.8+ KB

In [452]:
receipts.to_csv("receipts.csv",index=False)

In [453]:
items

,barcode,description,finalPrice,itemPrice,needsFetchReview,partnerItemId,preventTargetGapPoints,quantityPurchased,userFlaggedBarcode,userFlaggedNewItem,...,itemNumber,originalMetaBriteQuantityPurchased,pointsEarned,targetPrice,competitiveProduct,originalFinalPrice,originalMetaBriteItemPrice,deleted,priceAfterCoupon,metabriteCampaignId
0,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4011,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4011,ITEM NOT FOUND,1,1,NaN,1,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,028400642255,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,False,1,True,NaN,4011,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4011,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6936,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
6937,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
6938,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
6939,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
6940,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN

In [454]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6941 entries, 0 to 6940
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   barcode                             3090 non-null   object
 1   description                         6560 non-null   object
 2   finalPrice                          6767 non-null   object
 3   itemPrice                           6767 non-null   object
 4   needsFetchReview                    813 non-null    object
 5   partnerItemId                       6941 non-null   object
 6   preventTargetGapPoints              358 non-null    object
 7   quantityPurchased                   6767 non-null   float64
 8   userFlaggedBarcode                  337 non-null    object
 9   userFlaggedNewItem                  323 non-null    object
 10  userFlaggedPrice                    299 non-null    object
 11  userFlaggedQuantity                 299 non-null    float64
 12  receiptId                           6941 non-null   object
 13  needsFetchReviewReason              219 non-null    object
 14  pointsNotAwardedReason              340 non-null    object
 15  pointsPayerId                       1267 non-null   object
 16  rewardsGroup                        1731 non-null   object
 17  rewardsProductPartnerId             2269 non-null   object
 18  userFlaggedDescription              205 non-null    object
 19  originalMetaBriteBarcode            71 non-null     object
 20  originalMetaBriteDescription        10 non-null     object
 21  brandCode                           2600 non-null   object
 22  competitorRewardsGroup              275 non-null    object
 23  discountedItemPrice                 5769 non-null   object
 24  originalReceiptItemText             5760 non-null   object
 25  itemNumber                          153 non-null    object
 26  originalMetaBriteQuantityPurchased  15 non-null     float64
 27  pointsEarned                        927 non-null    object
 28  targetPrice                         378 non-null    object
 29  competitiveProduct                  645 non-null    object
 30  originalFinalPrice                  9 non-null      object
 31  originalMetaBriteItemPrice          9 non-null      object
 32  deleted                             9 non-null      object
 33  priceAfterCoupon                    956 non-null    object
 34  metabriteCampaignId                 863 non-null    object
dtypes: float64(3), object(32)
memory usage: 1.9+ MB

In [455]:
#Dropping rceeiptIds which are not present in receipt table
missing_receipts = items[~items['receiptId'].isin(receipts['receiptId'])]
items = items.drop(missing_receipts.index)

In [456]:
items['barcode'] = pd.to_numeric(items['barcode'], errors='coerce').fillna(0).astype(int)

In [457]:
items.isnull().sum()

barcode                                  0
description                            212
finalPrice                              55
itemPrice                               55
needsFetchReview                      4182
partnerItemId                            0
preventTargetGapPoints                4172
quantityPurchased                       55
userFlaggedBarcode                    4193
userFlaggedNewItem                    4202
userFlaggedPrice                      4222
userFlaggedQuantity                   4222
receiptId                                0
needsFetchReviewReason                4256
pointsNotAwardedReason                4117
pointsPayerId                         3417
rewardsGroup                          3055
rewardsProductPartnerId               2681
userFlaggedDescription                4264
originalMetaBriteBarcode              4282
originalMetaBriteDescription          4336
brandCode                             2523
competitorRewardsGroup                4170
discountedItemPrice                    866
originalReceiptItemText                868
itemNumber                            4193
originalMetaBriteQuantityPurchased    4332
pointsEarned                          3637
targetPrice                           4019
competitiveProduct                    3930
originalFinalPrice                    4337
originalMetaBriteItemPrice            4337
deleted                               4328
priceAfterCoupon                      3383
metabriteCampaignId                   3777
dtype: int64

In [458]:
items.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4337 entries, 0 to 6940
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   barcode                             4337 non-null   int64
 1   description                         4125 non-null   object
 2   finalPrice                          4282 non-null   object
 3   itemPrice                           4282 non-null   object
 4   needsFetchReview                    155 non-null    object
 5   partnerItemId                       4337 non-null   object
 6   preventTargetGapPoints              165 non-null    object
 7   quantityPurchased                   4282 non-null   float64
 8   userFlaggedBarcode                  144 non-null    object
 9   userFlaggedNewItem                  135 non-null    object
 10  userFlaggedPrice                    115 non-null    object
 11  userFlaggedQuantity                 115 non-null    float64
 12  receiptId                           4337 non-null   object
 13  needsFetchReviewReason              81 non-null     object
 14  pointsNotAwardedReason              220 non-null    object
 15  pointsPayerId                       920 non-null    object
 16  rewardsGroup                        1282 non-null   object
 17  rewardsProductPartnerId             1656 non-null   object
 18  userFlaggedDescription              73 non-null     object
 19  originalMetaBriteBarcode            55 non-null     object
 20  originalMetaBriteDescription        1 non-null      object
 21  brandCode                           1814 non-null   object
 22  competitorRewardsGroup              167 non-null    object
 23  discountedItemPrice                 3471 non-null   object
 24  originalReceiptItemText             3469 non-null   object
 25  itemNumber                          144 non-null    object
 26  originalMetaBriteQuantityPurchased  5 non-null      float64
 27  pointsEarned                        700 non-null    object
 28  targetPrice                         318 non-null    object
 29  competitiveProduct                  407 non-null    object
 30  originalFinalPrice                  0 non-null      object
 31  originalMetaBriteItemPrice          0 non-null      object
 32  deleted                             9 non-null      object
 33  priceAfterCoupon                    954 non-null    object
 34  metabriteCampaignId                 560 non-null    object
dtypes: float64(3), int64(1), object(31)
memory usage: 1.2+ MB

In [459]:
items['competitiveProduct'] = items['competitiveProduct'].astype('boolean')
items['competitiveProduct'] = items['competitiveProduct'].where(pd.notnull(items['competitiveProduct']), None)
items['deleted'] = items['deleted'].astype('boolean')
items['deleted'] = items['deleted'].where(pd.notnull(items['deleted']), None)
items['needsFetchReview'] = items['needsFetchReview'].astype('boolean')
items['needsFetchReview'] = items['needsFetchReview'].where(pd.notnull(items['needsFetchReview']), None)
items['preventTargetGapPoints'] = items['preventTargetGapPoints'].astype('boolean')
items['preventTargetGapPoints'] = items['preventTargetGapPoints'].where(pd.notnull(items['preventTargetGapPoints']), None)
items['userFlaggedNewItem'] = items['userFlaggedNewItem'].astype('boolean')
items['userFlaggedNewItem'] = items['userFlaggedNewItem'].where(pd.notnull(items['userFlaggedNewItem']), None)

In [460]:
items.to_csv("items.csv",index=False)